### ISSUE TITLE
Use the screenshot portal

### ISSUE THREAD

**Issue by danrabbit** [RajSolai/TextSnatcher#1]
Instead of having a sandbox hole to access the screenshot interface directly, your app should use the screenshot portal to request screenshots. You can use LibPortal to accomplish this: https://valadoc.org/libportal/Xdp.Portal.take_screenshot.html

**Comment by RajSolai** [comment]
Thanks a lot @danrabbit , Closing the issue as it is resolved with this pull request https://github.com/RajSolai/TextSnatcher/pull/4
