### ISSUE TITLE
Info button works only once

### ISSUE THREAD

**Issue by MrHeadwar** [RajSolai/TextSnatcher#11]
Hi,
A very minor bug : clicking on the (i) information button works the first time, but subsequent clicks give an empty/frozen window (with no buttons to close it).
Version 1.0.1, installed via FlatHub on Pop!_OS 21.10 64

**Comment by RajSolai** [comment]
Thanks a lot for filling the issue, I have resolved the bug in this commit 13cb67d1ce15af7bcb642ff7a4521bbf2a3ee861

**Comment by RajSolai** [comment]
Am Closing this issue as it is resolved, Thanks for your contribution :)
