### ISSUE TITLE
Screenshot not received error

### ISSUE THREAD

**Issue by hiren1771** [RajSolai/TextSnatcher#15]
linux mint cinnamon latest, installed flatpak. I run app, do screenshot, click share (as the usage video does on home page), and get the below error.

Failed to load module, why would flatpak not have this module fetched during install?

$ flatpak run com.github.rajsolai.textsnatcher
Gtk-Message: 14:53:26.332: Failed to load module "xapp-gtk3-module"
Process Done
** (com.github.rajsolai.textsnatcher:2): CRITICAL **: 14:53:42.651: TesseractTrigger.vala:75: Screenshot not received

**Comment by hiren1771** [comment]
Cannot find them in flatpak so I assume you meant on system package manager.
System package already has these installed:
libxapp1:amd64 2.2.8+una
xapps-common 2.2.8+una
I'm also not sure if that Gtk-Message Failed to load is a red herring, it might be a warning and not the cause?

**Comment by RajSolai** [comment]
Yes the xpp module missing error could be an warning however the portals does'nt seem to be stable on most of the DE. I am migrating to newer screenshots backend sooned, Thanks for your contribution you can give out your suggestions for screenshot backend / API on #16
