### ISSUE TITLE
dont let open more than 1 snatch now pop up

### ISSUE THREAD

**Issue by hitanol** [RajSolai/TextSnatcher#18]
video example https://fs-01.cyberdrop.to/simplescreenrecorder-2022-02-15_19.38.45-Htgi.mp4

**Comment by RajSolai** [comment]
Oops, Thanks a lot for Noticing the issue I will resolve it soon :)

**Comment by RajSolai** [comment]
Am closing this issue as the bug is resolved on commit 77ea18ef34bd77f0acb79b69f42c14157e8a6ea4 , Thanks a lot for your contribution :)
