### ISSUE TITLE
Remove '--filesystem=/home' persmission from manifest

### ISSUE THREAD

**Issue by danrabbit** [RajSolai/TextSnatcher#2]
This is an extremely broad permission that your app shouldn't need access to. If your app needs to save or open users' files, it should do so using the filechooser portal: https://valadoc.org/gtk+-3.0/Gtk.FileChooserNative.html

**Comment by RajSolai** [comment]
Sure @danrabbit I will remove the permission and narrow it down to usage of xdg-pictures

**Comment by RajSolai** [comment]
Thanks a lot @danrabbit , Closing the issue as it is solved by commit 4e888865d9985bd6b552cdf01e5a0a1db712fc91
