### ISSUE TITLE
Support for the Dutch language

### ISSUE THREAD

**Issue by perplexityjeff** [RajSolai/TextSnatcher#20]
Hi! I have been amazed by this application however I does seem to struggle a bit when using the Dutch language. Would be great to see this added as well. 

For now I can make it work by using English and just changing the things it got wrong.

Thanks in advance!

**Comment by RajSolai** [comment]
Sure Dutch will be added on the next release 2.0 ;)

**Comment by RajSolai** [comment]
As 2.0.0 release of TextSnatcher added support for Dutch Language am Closing this issue as solved.
