### ISSUE TITLE
No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop

### ISSUE THREAD

**Issue by R8s6** [RajSolai/TextSnatcher#21]
Hi,

Running on Arch the `textsnatcher-git`, I got this error:
```
$ textsnatcher
archtty
** (textsnatcher:203142): CRITICAL **: 12:40:38.143: TesseractTrigger.vala:124: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop
```

How to reproduce:
1. Install `textsnatcher-git` on Arch
2. Run textsnatcher, "Snatch Now" --> "Take Screenshot"

Could you please kindly investigate? Thanks!

**Comment by RajSolai** [comment]
What DE are you using Pal ?

**Comment by R8s6** [comment]
Xfce.

Thanks!

**Comment by RajSolai** [comment]
TextSnatcher uses freedesktop's Screenshot portal but it seems the portal is not fully stable in most of DEs. Hence TextSnatcher is moving to different method for screenshot #16 like scrot for X11 systems

**Comment by R8s6** [comment]
Thanks. When the fix is out, I'll definitely test it out. Thanks for the hard work!

**Comment by RajSolai** [comment]
The Release 2.0.0 of TextSnatcher uses scrot based screenshots for x11 system, now TextSnatcher can be used on all x11 based DEs.

**Comment by R8s6** [comment]
Thanks!

On Arch, both the `textsnatcher` (v2.0.0-1) and `textsnatcher-git` (the last-commit "git" version 2.0.0.r0.g7192ac1-1) still gave the same error:

```
** (textsnatcher:3101): CRITICAL **: 12:08:38.405: TesseractTrigger.vala:144: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop
```

Not sure if it's a packaging issue or not, I looked up the packging script ([PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=textsnatcher)) of `textsnatcher` and it seemed fairly straightforward:

```
...
pkgver=2.0.0
...
source=("$pkgname-$pkgver.tar.gz::https://github.com/RajSolai/TextSnatcher/archive/refs/tags/v$pkgver.tar.gz")

build() {
  arch-meson TextSnatcher-$pkgver build
  meson compile -C build
}

package() {
  meson install -C build --destdir "$pkgdir"

  ln -s "/usr/bin/com.github.rajsolai.$pkgname" "$pkgdir/usr/bin/$pkgname"
```

I also have `scrot` installed, tested on xfce (x11, not wayland).

Anything I can do to find out why still the same error?

Thanks!

**Comment by OnurKader** [comment]
Can you do `echo $XDG_SESSION_TYPE` and see if it returns `x11` or `X11`.

It might be `tty` if you're doing some `startx` related stuff.

[This](https://wiki.archlinux.org/title/Getty#Virtual_console) might help out, I haven't tested the config below but I hope it works for you.

```
[Service]
Environment=XDG_SESSION_TYPE=x11
```

You can call the file `/etc/systemd/system/getty@tty1.service.d/set_session_type.conf` of something.

**Comment by R8s6** [comment]
Oh that could be why.
```
$ $XDG_SESSION_TYPE
/dev/pts/1
```

I did use startx to auto-login during boot. I'll poke around and report back.

Thanks!

**Comment by R8s6** [comment]
@OnurKader 

Yes, I confirm it works out beautifully now.

I normally use the auto-login method described here:
https://wiki.archlinux.org/index.php/Getty#Automatic_login_to_virtual_console

Then I edited `/etc/systemd/system/getty@tty1.service.d/override.conf` by adding exactly what you suggested:
```
[Service]
Environment=XDG_SESSION_TYPE=x11
```

Reboot, and it works now.

Thank you so much!
