### ISSUE TITLE
Support for German

### ISSUE THREAD

**Issue by ActualDisaster2447** [RajSolai/TextSnatcher#22]
Good day!

I've been using your app for a while and loving it, although it seems to struggle with picking out German words, especially the Umlaute (Ä, ä, Ö, ö, Ü, ü) and the German specific _ß_ for _ss_. It would be very nice if your app could support these characters, otherwise it is doing a phenomenal job already just using the English language setting.

Thank you a lot for your great work and have nice day/night!

**Comment by RajSolai** [comment]
Thanks for Noticing me the issue and your feedback, the latest release (2.0.0) added support for German Language am Closing this issue as solved :)
