### ISSUE TITLE
Add OCR to categories

### ISSUE THREAD

**Issue by danrabbit** [RajSolai/TextSnatcher#3]
Instead of adding `OCR` to keywords, this is a valid category as defined [here](https://specifications.freedesktop.org/menu-spec/latest/apas02.html). You may want to also include `Graphics` and `Scanning`

**Comment by RajSolai** [comment]
Thanks for the reference @danrabbit. Closing the issue as the as it is resolved by commit  69ced8f5cb2870e9d5d4be8b89f84f75f5e1ee20
