### ISSUE TITLE
Option to select image from filesystem

### ISSUE THREAD

**Issue by Gaming4LifeDE** [RajSolai/TextSnatcher#7]
I think it's unnecessary to take a screenshot of an image, instead you should just be able to pick a photo from the filesystem.

Maybe also extend that idea to taking a webcam picture.

**Comment by RajSolai** [comment]
Yes I agree @Gaming4LifeDE picking up files to perform OCR would also be usefull including selecting image from clipboard, I have made a dialog for selecting the files / screenshoting / image in clipboard can you please provide your feedback on the design.

![Screenshot from 2022-02-11 21-43-41](https://user-images.githubusercontent.com/54436424/153628600-5157d068-eeda-4a41-a34c-6fcddb45f176.png)

**Comment by RajSolai** [comment]
Am Closing this issue as the v2.0.0 of application is implemented with a built-in file selector. Thanks for using the application and giving out feedback :)
