### ISSUE TITLE
Screenshot not working on KDE [FollowUp]

### ISSUE THREAD

**Issue by DistantThunder** [RajSolai/TextSnatcher#8]
# System information

* Operating System: Arch Linux
* KDE Plasma Version: 5.23.5
* KDE Frameworks Version: 5.90.0
* Qt Version: 5.15.2
* Kernel Version: 5.16.1-zen1-1-zen (64-bit)
* Graphics Platform: X11
* Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
* Memory: 62.7 Gio of RAM
* Graphics Processor: AMD Radeon RX 6900 XT
---
# Application
* Channel: Flatpak 
* Version: 1.0.0

# Problem

> The "Xdp.Portal.take_screenshot" function is broken on KDE. Can't take a single screenshot somehow, this may not be your fault though.

# Further information

```
https://imgur.com/a/ooXIFKh

Since I don't think it's actually your app failing, there are no relevant logs:

com.github.rajsolai.textsnatcher Gtk-Message: 18:24:22.170: Failed to load module "canberra-gtk-module" Process Done

Except it saying it's done its duty and called the actual screenshot tool.
```

**Comment by RajSolai** [comment]
I am closing the issue as the version 2.0.0 does not depend on portals for screenshot in X11 Systems. Thanks for trying out the application and giving feedback :)
