### ISSUE TITLE
Implement looking up the X11 clipboard for a picture [FollowUp][Enhancement]

### ISSUE THREAD

**Issue by DistantThunder** [RajSolai/TextSnatcher#9]
# Premise
Right now, the application relies on XDG standards to call a platform native screenshot tool to provide it with the image to work on.

# Limits
That method has shown some limit, and it can be inferred that not all  DE/WM would have implemented such standards or would have done so the correct. Although this is not the responsibility of this  application, it would be nice to provide end-users with a different way of loading pictures into the application.

# Proposal
I thus propose, that the application be able to look at the most recent / top item of the DE clipboard (X11 or Wayland agnostic if possible) and upon a quick check, determine the type of the object there and load it if it's an image in the proper format.

Ideally, this implementation would be non-blocking and asynchronous so as not to block the UI, as some DE framework can make you wait a long time before returning any answer.

**Comment by DistantThunder** [comment]
This looks good to me but I wonder if it's necessary to make it a second window? Why not put directly all this in the startup screen?

The "Snatch Now!" dialog then this screen feels unnecessarily to me.

**Comment by RajSolai** [comment]
True, Having multiple windows might confuse the user and degrade the UX hence instead of a dialog all options are now displayed in the main window itself. I will share a screenshot of implementation.

**Comment by RajSolai** [comment]
Thanks for your support and feedback Pal, Iam closing this issue as release 2.0.0 included options for image selection and clipboard for OCR Operation.

**Comment by DistantThunder** [comment]
Thanks to you! Very cool project!
